#!/bin/bash
# ──────────────────────────────────────────────────────────────────
# 🍕 Dorito Pizza — One-command deploy
#
# Usage:
#   git clone https://github.com/rajatpoddar/Dorito-Pizza.git
#   cd Dorito-Pizza
#   bash deploy.sh
# ──────────────────────────────────────────────────────────────────

# ── Colors (POSIX-safe: use actual bytes, not escape strings) ────
RED=$'\033[0;31m'
GREEN=$'\033[0;32m'
YELLOW=$'\033[1;33m'
CYAN=$'\033[0;36m'
BOLD=$'\033[1m'
DIM=$'\033[2m'
NC=$'\033[0m'

step()  { printf "\n  ${CYAN}${BOLD}▸ %s${NC}\n" "$1"; }
info()  { printf "    ${GREEN}✔${NC} %s\n" "$1"; }
warn()  { printf "    ${YELLOW}⚠${NC} %s\n" "$1"; }
die()   { printf "\n  ${RED}${BOLD}FATAL:${NC} %s\n\n" "$1" >&2; exit 1; }

# ── Banner ──────────────────────────────────────────────────────
printf "
  ${BOLD}${CYAN}╔══════════════════════════════════════════════════════╗
  ║                                                      ║
  ║       🍕  D O R I T O   P I Z Z A  🍕               ║
  ║       One-Command Deploy Script                      ║
  ║                                                      ║
  ╚══════════════════════════════════════════════════════╝${NC}
"

# ── Pre-flight ──────────────────────────────────────────────────
step "Pre-flight checks"

docker --version >/dev/null 2>&1 || die "Docker not found. Install Docker first."
git --version >/dev/null 2>&1 || die "Git not found."
curl --version >/dev/null 2>&1 || die "curl not found."
openssl version >/dev/null 2>&1 || die "openssl not found."

info "All tools available"

# ── Auto git pull ──────────────────────────────────────────────
step "Pulling latest code"

if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    LOCAL=$(git rev-parse HEAD 2>/dev/null)
    git fetch origin main --quiet 2>/dev/null
    REMOTE=$(git rev-parse origin/main 2>/dev/null)

    if [ "$LOCAL" = "$REMOTE" ]; then
        info "Already up-to-date (${LOCAL:0:7})"
    else
        BEHIND=$(git rev-list HEAD..origin/main --count 2>/dev/null || echo "?")
        info "Pulling $BEHIND new commit(s) ..."
        git pull origin main --quiet 2>/dev/null || die "git pull failed"
        info "Updated to ${GREEN}$(git rev-parse --short HEAD)${NC}"
    fi
else
    warn "Not a git repo — skipping pull"
fi

# ── Stop existing containers ───────────────────────────────────
step "Stopping existing containers"

if docker compose ps 2>/dev/null | grep -q "dorito-"; then
    info "Found running containers — stopping ..."
    docker compose down --remove-orphans 2>/dev/null || true
    sleep 2
    info "Containers stopped"
else
    info "No existing containers running"
fi

# ── Port detection ──────────────────────────────────────────────
step "Detecting free ports"

port_free() {
    ! netstat -tlnp 2>/dev/null | grep -q ":${1} "
}

pick_port() {
    for p in "$@"; do
        if port_free "$p"; then
            echo "$p"
            return
        fi
    done
    echo "$1"  # fallback to first candidate
}

BACKEND_PORT="${BACKEND_PORT:-$(pick_port 8555 8556 8557 8558)}"
FRONTEND_PORT="${FRONTEND_PORT:-$(pick_port 8580 8581 8582 8583)}"
DB_PORT="${DB_PORT:-$(pick_port 5433 5434 5435 5437)}"

printf "    Backend:   ${GREEN}%s${NC}\n" ":$BACKEND_PORT"
printf "    Frontend:  ${GREEN}%s${NC}\n" ":$FRONTEND_PORT"
printf "    Database:  ${GREEN}%s${NC}\n" ":$DB_PORT"
info "Ports allocated"

# ── .env ────────────────────────────────────────────────────────
step "Environment configuration"

if [ ! -f .env ]; then
    info "Generating .env with random secrets ..."
    SECRET_KEY=$(openssl rand -hex 32)
    JWT_SECRET_KEY=$(openssl rand -hex 32)
    DB_PASS=$(openssl rand -base64 24 | tr -d '/+=')

    cat > .env <<EOF
# Auto-generated by deploy.sh — $(date -u +"%Y-%m-%d %H:%M:%S UTC")
SECRET_KEY=${SECRET_KEY}
JWT_SECRET_KEY=${JWT_SECRET_KEY}
POSTGRES_USER=dorito
POSTGRES_PASSWORD=${DB_PASS}
POSTGRES_DB=dorito
DATABASE_URL=postgresql+psycopg2://dorito:${DB_PASS}@db:5432/dorito
BACKEND_PORT=${BACKEND_PORT}
FRONTEND_PORT=${FRONTEND_PORT}
DB_PORT=${DB_PORT}
SENTRY_DSN=
SENTRY_TRACES_SAMPLE_RATE=0.1
GIT_COMMIT_SHA=$(git rev-parse --short HEAD 2>/dev/null || echo unknown)
EOF
    info ".env created"
else
    info ".env exists — updating ports only"
    for var in BACKEND_PORT FRONTEND_PORT DB_PORT; do
        val="${!var}"
        if grep -q "^${var}=" .env 2>/dev/null; then
            sed -i.bak "s|^${var}=.*|${var}=${val}|" .env && rm -f .env.bak
        else
            echo "${var}=${val}" >> .env
        fi
    done
fi

# ── Build ───────────────────────────────────────────────────────
step "Building Docker images"
docker compose build --progress=plain 2>&1 | while IFS= read -r line; do
    # Show build stage headers and progress
    if echo "$line" | grep -qE "^#\[linux"; then
        printf "    ${DIM}%s${NC}\n" "$line"
    elif echo "$line" | grep -qE "=>|FINISHED|CACHED|ERROR"; then
        printf "    ${DIM}%s${NC}\n" "$line"
    fi
done
info "Build complete"

# ── Launch ──────────────────────────────────────────────────────
step "Starting containers"
docker compose up -d 2>&1
info "Containers started"

# ── Health check ────────────────────────────────────────────────
step "Health check"

HEALTH_URL="http://localhost:${BACKEND_PORT}/api/health"
for i in $(seq 1 60); do
    if curl -fsS "$HEALTH_URL" >/dev/null 2>&1; then
        info "Backend healthy! (took $((i*2))s)"
        break
    fi
    if [ "$i" -eq 60 ]; then
        warn "Backend not healthy after 120s — check: docker compose logs backend"
    fi
    sleep 2
done

# ── Status ──────────────────────────────────────────────────────
step "Container status"
docker compose ps 2>/dev/null

# ── Summary ─────────────────────────────────────────────────────
SERVER_IP=$(hostname -I 2>/dev/null | awk '{print $1}')
SERVER_IP="${SERVER_IP:-localhost}"

printf "
  ${GREEN}${BOLD}═══════════════════════════════════════════════════
   🍕  DORITO PIZZA IS LIVE!
  ═══════════════════════════════════════════════════${NC}

  Frontend:   ${CYAN}http://${SERVER_IP}:${FRONTEND_PORT}${NC}
  Backend:    ${CYAN}http://${SERVER_IP}:${BACKEND_PORT}/api/health${NC}
  DB (dev):   ${DIM}localhost:${DB_PORT}${NC}

  ${DIM}Commands:${NC}
    docker compose logs -f       # tail logs
    docker compose down          # stop all
    bash deploy.sh               # redeploy
"
