#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────
# Dorito Pizza — One-command deploy
#
# Usage:
#   git clone https://github.com/rajatpoddar/Dorito-Pizza.git
#   cd Dorito-Pizza
#   bash deploy.sh
#
# The script:
#   1. Detects free ports (8555/8580/5433) or lets you override via env vars.
#   2. Generates a .env with secure secrets if one doesn't exist.
#   3. Builds and starts the 3-service Docker stack.
#   4. Waits for the backend health check.
# ──────────────────────────────────────────────────────────────────
set -euo pipefail

# ── Colour helpers ───────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
die()   { echo -e "${RED}[FATAL]${NC} $*" >&2; exit 1; }

# ── Pre-flight checks ──────────────────────────────────────────
command -v docker >/dev/null 2>&1 || die "docker not found. Install Docker first."
docker compose version >/dev/null 2>&1 || die "docker compose (v2) not found."

# ── Free-port detection ─────────────────────────────────────────
# Checks if a port is already in use; returns the port if free,
# otherwise tries the next candidate.
port_is_used() {
    local port=$1
    netstat -tlnp 2>/dev/null | grep -qE ":${port} " && return 0 || return 1
}

find_free_port() {
    local -a candidates=("$@")
    for p in "${candidates[@]}"; do
        if ! port_is_used "$p"; then
            echo "$p"; return 0
        fi
    done
    die "All candidate ports in use: ${candidates[*]}"
}

# If user already set ports via env, respect them; otherwise auto-detect.
BACKEND_PORT="${BACKEND_PORT:-$(find_free_port 8555 8556 8557 8558 8559 8560)}"
FRONTEND_PORT="${FRONTEND_PORT:-$(find_free_port 8580 8581 8582 8583 8584 8585)}"
DB_PORT="${DB_PORT:-$(find_free_port 5433 5434 5435 5437 5438 5439)}"

info "Using ports — backend:${BACKEND_PORT}  frontend:${FRONTEND_PORT}  db:${DB_PORT}"

# ── Generate .env if missing ────────────────────────────────────
if [ ! -f .env ]; then
    info "Generating .env with random secrets …"
    SECRET_KEY=$(openssl rand -hex 32)
    JWT_SECRET_KEY=$(openssl rand -hex 32)
    POSTGRES_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=')

    cat > .env <<ENVEOF
# ── Dorito Pizza — Auto-generated by deploy.sh ──
SECRET_KEY=${SECRET_KEY}
JWT_SECRET_KEY=${JWT_SECRET_KEY}
POSTGRES_USER=dorito
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=dorito
DATABASE_URL=postgresql+psycopg2://dorito:${POSTGRES_PASSWORD}@db:5432/dorito

# ── Ports (override before running deploy.sh if needed) ──
BACKEND_PORT=${BACKEND_PORT}
FRONTEND_PORT=${FRONTEND_PORT}
DB_PORT=${DB_PORT}

# ── Observability (optional) ──
SENTRY_DSN=
SENTRY_TRACES_SAMPLE_RATE=0.1
GIT_COMMIT_SHA=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
ENVEOF
    info ".env created."
else
    info ".env already exists — skipping generation."
    # Ensure port vars are exported from existing .env
    set -a; source .env; set +a
fi

# ── Build & launch ──────────────────────────────────────────────
info "Building and starting containers …"
docker compose up -d --build

# ── Health check ────────────────────────────────────────────────
info "Waiting for backend health check …"
HEALTH_URL="http://localhost:${BACKEND_PORT}/api/health"
for i in $(seq 1 60); do
    if curl -fsS "$HEALTH_URL" >/dev/null 2>&1; then
        info "Backend healthy after ${i}*2s ✓"
        break
    fi
    if [ "$i" -eq 60 ]; then
        die "Backend did not become healthy in 120 s. Check: docker compose logs backend"
    fi
    sleep 2
done

# ── Summary ─────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  🍕  Dorito Pizza is live!${NC}"
echo -e "${GREEN}════════════════════════════════════════════════════${NC}"
echo ""
echo -e "  Frontend:  ${YELLOW}http://$(hostname -I | awk '{print $1}'):${FRONTEND_PORT}${NC}"
echo -e "  Backend:   ${YELLOW}http://$(hostname -I | awk '{print $1}'):${BACKEND_PORT}/api/health${NC}"
echo -e "  DB (dev):  ${YELLOW}localhost:${DB_PORT}${NC}"
echo ""
echo -e "  Logs:      ${YELLOW}docker compose logs -f${NC}"
echo -e "  Stop:      ${YELLOW}docker compose down${NC}"
echo -e "  Restart:   ${YELLOW}bash deploy.sh${NC}"
echo ""
